config/routes.rb
Rails.application.routes.draw do
  get 'patients/index'
  devise_for :users

  ActiveAdmin.routes(self)

  authenticated :user, ->(user) { user.has_role?(:patient) } do
    root to: "patients#index", as: :patient_root
    
    resources :doctors, only: [:index] do
      resources :appointments, only: [:index, :show]
    end
  end

  authenticated :user, ->(user) { user.has_role?(:doctor) } do
    root to: "doctors#index", as: :doctor_root
    
    resources :patients, only: [:index] do
      resources :appointments, only: [:index, :show, :destroy]
    end
  end

  resources :appointments, only: [:index, :show, :new, :create, :update, :destroy] do
    delete :destroy, on: :member
    member do
      get :edit
    end
  end

  namespace :doctors do
    resources :appointments, only: [:index, :edit, :update]
  end

  root to: "profiles#index"
  match '*unmatched', to: 'application#not_found_method', via: :all
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user) 
    return unless user.present?

    if user.admin?
      can :read, Patient
      can :manage, Doctor
      can :manage, Admin
      can :manage, Category
      can :read, Appointment
    end

    if user.doctor?
      can :read, Patient
      can [:read, :update], Doctor
      can :read, Category
      can [:read, :update], Appointment

      cannot :manage, Admin
    end

    if user.patient?
      can :read, Patient
      can :read, Doctor
      can :read, Category
      can [:read, :create, :destroy], Appointment

      cannot :manage, Admin
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor, class_name: 'User', foreign_key: 'doctor_id'
  belongs_to :patient, class_name: 'User', foreign_key: 'patient_id'

  enum status: { open: 'open', closed: 'closed' }
  validates :status, presence: true, inclusion: { in: Appointment.statuses.keys }
  validate :validate_max_open_appointments, on: :create

  def close(recommendations)
    self.status = :closed
    self.recommendations = recommendations
    save
  end

  MAX_OPEN_APPOINTMENTS = 10

  private

  def validate_max_open_appointments
    return unless doctor && doctor.appointments_as_doctor.open.count >= MAX_OPEN_APPOINTMENTS

    errors.add(:doctor_id, "has reached the maximum number of open appointments.")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :doctors, class_name: 'User', foreign_key: 'category_id'
  validates :name, presence: true, length: { maximum: 30 }
end

app/models/doctor.rb
class Doctor < User
  has_many :appointments, dependent: :destroy, foreign_key: 'doctor_id'
  has_many :patients, through: :appointments
  belongs_to :category, optional: true
end

app/models/patient.rb
class Patient < User
  has_many :appointments, dependent: :destroy, foreign_key: 'patient_id'
  has_many :doctors, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :category, optional: true
  has_many :appointments_as_doctor, class_name: 'Appointment', foreign_key: 'doctor_id'
  has_many :appointments_as_patient, class_name: 'Appointment', foreign_key: 'patient_id'

  validates :phone, uniqueness: true
  validates :full_name, presence: true
  
  enum role: { admin: "admin", doctor: "doctor", patient: "patient" }

  def has_role?(role)
    self.role == role.to_s
  end

  def email_required?
    false
  end
  
  def email_changed?
    false
  end

  def password_required?
    new_record? || password.present?
  end

  def password_match?
    password.blank? || password_confirmation.present?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Draper::ViewHelpers
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "You are not authorized to access this page."
  end
  
  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.superadmin?
      flash[:alert] = "Unauthorized Access!"
      redirect_to new_user_session_path
    end
  end
  
  def current_admin_user
    return unless current_user&.superadmin?
    current_user
  end
  
  def after_sign_in_path_for(resource)
    if resource.superadmin
      admin_dashboard_path
    else
      super
    end
  end

  def not_found_method
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :role])
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  include Draper::Decoratable

  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.patient?
      @appointments = current_user.appointments_as_patient
    elsif current_user.doctor?
      @appointments = current_user.appointments_as_doctor
    else
      @appointments = Appointment.all
    end
  end

  def show
  end

  def new
    authorize! :new, @appointment
    @appointment = Appointment.new
    @doctors = User.where(role: 'doctor').decorate
    @patients = User.where(role: 'patient')
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.status = :open

    if @appointment.save
      redirect_to appointments_path, notice: 'Appointment was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @appointment
  end

  def update
    authorize! :update, @appointment
    if @appointment.update(appointment_params.merge(status: "closed"))
      redirect_to appointments_path, notice: 'Appointment closed.'
    else
      render :edit
    end
  end

  def destroy
    if @appointment.open?
      @appointment.destroy
      redirect_to appointments_path, notice: 'Appointment deleted successfully.'
    else
      redirect_to appointment_path(@appointment), alert: 'Closed appointments cannot be deleted.'
    end
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :recommendations, :status)
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # load_and_authorize_resource
  
  def index
    
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # load_and_authorize_resource
  before_action :authenticate_user!
  def index
    @doctors = Doctor.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/edit.html.erb
<div class="container m-4">
  <% if @appointment.status == 'open' %>
    <%= form_with(model: @appointment) do |form| %>
      <div class="field">
        <%= form.label :recommendations %>
        <%= form.text_area :recommendations %>
      </div>
      
      <div class="actions">
        <%= form.submit 'Leave Recommendation' %>
      </div>
    <% end %>
  <% else %>
    <p>Recommendations: <%= @appointment.recommendations %></p>
  <% end %>
</div>

app/views/appointments/index.html.erb
<div class="container m-2">
  <h1>Your Appointments</h1>

  <% if @appointments.any? %>
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Date</th>
          <% unless current_user.patient? %>
            <th>Patient</th>
          <% end %>
          <% unless current_user.doctor? %>
            <th>Doctor</th>
          <% end %>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @appointments.each_with_index do |appointment, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= appointment.created_at.strftime("%Y-%m-%d %H:%M") %></td>
            <% if current_user.doctor? %>
              <td><%= appointment.patient.full_name if appointment.patient %></td>
            <% end %>
            <% unless current_user.doctor? %>
              <td><%= appointment.doctor.full_name %></td>
            <% end %>
            <td><%= appointment.status %></td>
            <td>
              <% if appointment.open? %>
                <% if current_user.patient? %>
                  <%= button_to appointment_path(appointment), method: :delete, onclick: "return confirm('Are you sure you want to delete this appointment?')", class: "btn btn-sm btn-danger", form: { class: "d-inline" } do %>
                    Delete
                  <% end %>
                <% elsif current_user.doctor? %>
                  <%= link_to "Leave Recommendation", edit_appointment_path(appointment), class: "btn btn-sm btn-primary" %>
                <% end %>
              <% else %>
                <%= link_to "Details", appointment_path(appointment.id), class: "btn btn-sm btn-primary" %>
              <% end %>
            
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>You have no appointments so far.</p>
  <% end %>
</div>

app/views/appointments/new.html.erb
<div class="container m-4">
  <h1>New Appointment</h1>

  <%= form_with model: @appointment, url: appointments_path, method: :post do |form| %>
    <div class="field">
      <%= form.label :doctor_id %>
      <%= form.collection_select :doctor_id, @doctors, :id, :full_name_with_category, prompt: "Select a doctor" %>
    </div>

    <% if current_user&.patient? %>
      <%= form.hidden_field :patient_id, value: current_user.id %>
    <% else %>
      <div class="field">
        <%= form.label :patient_id %>
        <%= form.collection_select :patient_id, @patients, :id, :full_name, prompt: "Select a patient" %>
      </div>
    <% end %>

    <% unless current_user.patient? %>
      <div class="field">
        <%= form.label :recommendations %>
        <%= form.text_area :recommendations %>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit "Create Appointment" %>
    </div>
  <% end %>
</div>

app/views/appointments/show.html.erb
<div class="container m-4">
  <% if @appointment.status == 'open' %>
    <%= form_with(model: @appointment, url: close_appointment_path(@appointment), method: :patch) do |form| %>
      <div class="field">
        <%= form.label :recommendations %>
        <%= form.text_area :recommendations %>
      </div>
      
      <div class="actions">
        <%= form.submit 'Close Appointment' %>
      </div>
    <% end %>
  <% else %>
    <p>Recommendations: <%= @appointment.recommendations %></p>
  <% end %>
</div>

app/views/doctors/index.html.erb
<div class="container m-4">
  <h1>Hello, dr. <%= current_user.full_name %></h1>
    <% if current_user.appointments_as_doctor.open.any? %>
      <p>You have <%= current_user.appointments_as_doctor.open.count %> open appointment(s).</p>
      <%= link_to "View Appointments", appointments_path(@appointments), class: "btn btn-primary" %>
    <% else %>
      <p>You don't have any appointments yet.</p>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="container m-4">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to "OurClinic", root_path, class: "nav-link" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Appointments", appointments_path(@appointments), class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clinic2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key.to_s == 'notice' ? 'success' : 'danger' %>">
          <%= value %>
        </div>
      <% end %>
      
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/patients/index.html.erb
<div class="container m-4">
<%= link_to 'Create Appointment', new_appointment_path(@appointment), class: "btn btn-light" %>
<%= link_to "View Appointments", appointments_path(@appointments), class: "btn btn-light" %>
  <h1>List of Doctors</h1>
  <table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Doctor Name</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @doctors.each_with_index do |doctor, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= doctor.try(:full_name) || "" %></td>
        <td><%= doctor.category.try(:name) || "" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/profiles/index.html.erb
<div class="container m-4 index-page">
  <div class="m-4">
    <h1>Welcome to Our Clinic</h1>
  </div>
  <div class="d-flex justify-content-center align-items-center m-4">
    <div class="container" style="max-width: 300px; margin-top: 40px;">

        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="https://res.cloudinary.com/dpz9dn6cr/image/upload/v1685621182/samples/imagecon-group.jpg" class="d-block w-100" alt="team1">
            </div>
            <div class="carousel-item">
              <img src="https://res.cloudinary.com/dpz9dn6cr/image/upload/v1685621175/samples/animals/three-dogs.jpg" class="d-block w-100" alt="dogs">
            </div>
            <div class="carousel-item">
              <img src="https://res.cloudinary.com/dpz9dn6cr/image/upload/v1685621173/samples/people/boy-snow-hoodie.jpg" class="d-block w-100" alt="child">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
  </div>  
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase %> from being saved:</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>